export { Hero } from "./Hero";
export { FeaturedCaseStudy } from "./FeaturedCaseStudy";
export { ProductCarousel } from "./ProductCarousel";
export { ServicesScrolly } from "./ServicesScrolly";
export { ServicesSlider } from "./ServicesSlider";
export { OurSoftware } from "./OurSoftware";
export { ManifestoBand } from "./ManifestoBand";
export { Testimonials } from "./Testimonials";
export { SplitCTA } from "./SplitCTA";
